# This is a basic workflow to help you get started with Actions

name: Java CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build